# flask-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: your-backend-image
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_DB
          value: "taskdb"
        - name: POSTGRES_USER
          value: "taskuser"
        - name: POSTGRES_PASSWORD
          value: "taskpassword"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"

---
# flask-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  type: NodePort
  selector:
    app: flask-backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001  # You can modify the node port as needed
