apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  type: ClusterIP  # Ensure this is set for internal communication
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask-backend