# flask-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  type: NodePort
  selector:
    app: flask-backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 5000  # You can modify the node port as needed