# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "taskdb"
        - name: POSTGRES_USER
          value: "taskuser"
        - name: POSTGRES_PASSWORD
          value: "taskpassword"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-pv
          subPath: data
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: cloudru-pvc